"""Add OAuth, email verification, and enhanced role management to users

Revision ID: 20251228_oauth_roles
Revises: increase_sample_id_length
Create Date: 2025-12-28 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20251228_oauth_roles'
down_revision = 'f26d9f48a50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # OAuth Support
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('oauth_data', sa.JSON, nullable=True))

        # Email Verification
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('verification_token_expiry', sa.DateTime(), nullable=True))

        # Password Reset
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token_expiry', sa.DateTime(), nullable=True))

        # Enhanced Role Management
        batch_op.alter_column('role',
                            existing_type=sa.String(length=20),
                            type_=sa.String(length=30),
                            existing_nullable=False,
                            server_default='viewer')
        batch_op.add_column(sa.Column('role_status', sa.String(length=20), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('role_requested', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('role_approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('role_approved_date', sa.DateTime(), nullable=True))

        # Organization Details
        batch_op.add_column(sa.Column('organization_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('organization_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))

        # Site Assignments (for Site Manager, Industry Partner roles)
        batch_op.add_column(sa.Column('assigned_sites', sa.JSON, nullable=True))

        # Make password_hash nullable for OAuth users
        batch_op.alter_column('password_hash',
                            existing_type=sa.String(length=256),
                            nullable=True)

        # Create indexes
        batch_op.create_index('ix_users_oauth_provider_id', ['oauth_provider', 'oauth_id'], unique=False)
        batch_op.create_index('ix_users_verification_token', ['verification_token'], unique=False)
        batch_op.create_index('ix_users_password_reset_token', ['password_reset_token'], unique=False)
        batch_op.create_index('ix_users_role_status', ['role', 'role_status'], unique=False)

        # Create foreign key for role_approved_by_id
        batch_op.create_foreign_key('fk_users_role_approved_by', 'users', ['role_approved_by_id'], ['id'])

    # Update existing users to have email_verified=True (assume existing users are verified)
    op.execute("UPDATE users SET email_verified = true WHERE email_verified = false")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Drop foreign key
        batch_op.drop_constraint('fk_users_role_approved_by', type_='foreignkey')

        # Drop indexes
        batch_op.drop_index('ix_users_role_status')
        batch_op.drop_index('ix_users_password_reset_token')
        batch_op.drop_index('ix_users_verification_token')
        batch_op.drop_index('ix_users_oauth_provider_id')

        # Revert password_hash to NOT NULL (set empty hash for OAuth users first)
        op.execute("UPDATE users SET password_hash = 'oauth_user_no_password' WHERE password_hash IS NULL")
        batch_op.alter_column('password_hash',
                            existing_type=sa.String(length=256),
                            nullable=False)

        # Drop new columns
        batch_op.drop_column('assigned_sites')
        batch_op.drop_column('job_title')
        batch_op.drop_column('organization_type')
        batch_op.drop_column('organization_name')
        batch_op.drop_column('role_approved_date')
        batch_op.drop_column('role_approved_by_id')
        batch_op.drop_column('role_requested')
        batch_op.drop_column('role_status')

        # Revert role column size
        batch_op.alter_column('role',
                            existing_type=sa.String(length=30),
                            type_=sa.String(length=20),
                            existing_nullable=False)

        batch_op.drop_column('password_reset_token_expiry')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('verification_token_expiry')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('oauth_data')
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')
    # ### end Alembic commands ###
