"""Add role_permissions table for granular access control

Revision ID: 20251228_role_perms
Revises: 20251228_oauth_roles
Create Date: 2025-12-28 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251228_role_perms'
down_revision = '20251228_oauth_roles'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=30), nullable=False),

        # View Permissions
        sa.Column('can_view_sites', sa.Boolean(), nullable=True, server_default='true'),
        sa.Column('can_view_samples', sa.Boolean(), nullable=True, server_default='true'),
        sa.Column('can_view_test_results', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_view_analysis', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_export_data', sa.Boolean(), nullable=True, server_default='false'),

        # Create/Edit Permissions - Sites
        sa.Column('can_create_sites', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_edit_sites', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_delete_sites', sa.Boolean(), nullable=True, server_default='false'),

        # Create/Edit Permissions - Samples
        sa.Column('can_create_samples', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_edit_samples', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_delete_samples', sa.Boolean(), nullable=True, server_default='false'),

        # Create/Edit Permissions - Test Results
        sa.Column('can_submit_test_results', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_edit_test_results', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_delete_test_results', sa.Boolean(), nullable=True, server_default='false'),

        # Visual Observations
        sa.Column('can_submit_visual_observations', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_edit_visual_observations', sa.Boolean(), nullable=True, server_default='false'),

        # ML & Analysis
        sa.Column('can_run_ml_models', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_create_analysis', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_view_ml_predictions', sa.Boolean(), nullable=True, server_default='false'),

        # Admin Functions
        sa.Column('can_manage_users', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_approve_roles', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_approve_submissions', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_bulk_import', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('can_manage_system', sa.Boolean(), nullable=True, server_default='false'),

        # Data Scope
        sa.Column('data_scope', sa.String(length=20), nullable=False, server_default='public'),

        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('role')
    )
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
