"""Add visitor tracking tables

Revision ID: 662657ac3ecc
Revises: d5c911bf9cb7
Create Date: 2025-12-07 00:44:31.523699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662657ac3ecc'
down_revision = 'd5c911bf9cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referer', sa.String(length=500), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_timestamp'))
        batch_op.drop_index(batch_op.f('ix_visits_session_id'))
        batch_op.drop_index(batch_op.f('ix_visits_ip_address'))

    op.drop_table('visits')
    op.drop_table('visitor_stats')
    # ### end Alembic commands ###
