"""Add VisualObservation model

Revision ID: 9e30ac691a3b
Revises: 
Create Date: 2025-12-05 21:53:06.389170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e30ac691a3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('observation_time', sa.Time(), nullable=True),
    sa.Column('observer_name', sa.String(length=100), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('photo_filename', sa.String(length=255), nullable=True),
    sa.Column('photo_format', sa.String(length=10), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('water_color', sa.String(length=50), nullable=True),
    sa.Column('water_clarity', sa.String(length=50), nullable=True),
    sa.Column('water_odor', sa.String(length=50), nullable=True),
    sa.Column('surface_condition', sa.String(length=50), nullable=True),
    sa.Column('algae_presence', sa.String(length=30), nullable=True),
    sa.Column('floating_debris', sa.Boolean(), nullable=True),
    sa.Column('dead_fish', sa.Boolean(), nullable=True),
    sa.Column('visible_pollution', sa.Boolean(), nullable=True),
    sa.Column('pollution_type', sa.String(length=100), nullable=True),
    sa.Column('water_level', sa.String(length=30), nullable=True),
    sa.Column('bank_condition', sa.String(length=50), nullable=True),
    sa.Column('weather', sa.String(length=50), nullable=True),
    sa.Column('recent_rainfall', sa.Boolean(), nullable=True),
    sa.Column('visual_quality_rating', sa.Integer(), nullable=True),
    sa.Column('concerns_noted', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(length=200), nullable=True),
    sa.Column('analysis_status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['water_samples.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visual_observations')
    # ### end Alembic commands ###
