"""Add country field to sites table

Revision ID: a1b2c3d4e5f6
Revises: 662657ac3ecc
Create Date: 2025-12-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '662657ac3ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add country column with default 'India' for existing sites
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False, server_default='India'))
        batch_op.create_index(batch_op.f('ix_sites_country'), ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_country'))
        batch_op.drop_column('country')
    # ### end Alembic commands ###
