"""Add drift_detections table

Revision ID: d5c911bf9cb7
Revises: 9e30ac691a3b
Create Date: 2025-12-06 15:49:27.174109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c911bf9cb7'
down_revision = '9e30ac691a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('detection_timestamp', sa.DateTime(), nullable=True),
    sa.Column('parameter_name', sa.String(length=50), nullable=False),
    sa.Column('drift_detected', sa.Boolean(), nullable=True),
    sa.Column('drift_direction', sa.String(length=20), nullable=True),
    sa.Column('drift_magnitude_sigma', sa.Float(), nullable=True),
    sa.Column('cusum_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('baseline_mean', sa.Float(), nullable=True),
    sa.Column('baseline_std', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['water_samples.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drift_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drift_detections_detection_timestamp'), ['detection_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_drift_detections_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drift_detections_site_id'), ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drift_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drift_detections_site_id'))
        batch_op.drop_index(batch_op.f('ix_drift_detections_sample_id'))
        batch_op.drop_index(batch_op.f('ix_drift_detections_detection_timestamp'))

    op.drop_table('drift_detections')
    # ### end Alembic commands ###
